ElectroMart/Models/InputModel/Brand.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ElectroMart.Models.InputModel
{
    public class Brand
    {
        public int Id { get; set; }
        [ForeignKey("Category")]
        [Display(Name = "Category")]
        public int CategoryId { get; set; }
        [ForeignKey("SubCategory"), Display(Name = "Sub Category")]
        public int SubCategoryId { get; set; }
        [Display(Name = "Brand")]
        public string BrandName { get; set; }

        //nev
        public virtual Category Category { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        public virtual ICollection<Product> Products { get; set; } = new List<Product>();
    }
}

ElectroMart/Models/InputModel/Category.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Drawing.Drawing2D;
using System.Linq;
using System.Web;

namespace ElectroMart.Models.InputModel
{
    public class Category
    {
        public int Id { get; set; }
        [Required, Display(Name = "Category")]
        public string CategoryName { get; set; }
        [Required, Display(Name = "Description")]
        public string CategoryDescription { get; set; }

        //nev
        public virtual ICollection<SubCategory> SubCategories { get; set; } = new List<SubCategory>();
        public virtual ICollection<Brand> Brands { get; set; } = new List<Brand>();
        public virtual ICollection<Product> Products { get; set; } = new List<Product>();
    }
}

ElectroMart/Controllers/BrandController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ElectroMart.Models.InputModel;
using PagedList;

namespace ElectroMart.Controllers
{
    public class BrandController : Controller
    {
        private EcommerceDbContext db = new EcommerceDbContext();

        // GET: Brand
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name" : "";

            ViewBag.CategorySortParm = String.IsNullOrEmpty(sortOrder) ? "category" : "";
            ViewBag.SubCategorySortParm = String.IsNullOrEmpty(sortOrder) ? "subcategory" : "";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var brand = from s in db.Brands
                        select s;
            var category = from c in db.Categories select c;
            var subcategory = from s in db.SubCategories select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                brand = brand.Where(x => x.BrandName.ToLower().StartsWith(searchString.ToLower()));


            }
            switch (sortOrder)
            {
                case "name":
                    brand = brand.OrderBy(b => b.BrandName);
                    break;

                default:  // Name des_cending 
                    brand = brand.OrderByDescending(s => s.BrandName);
                    category = category.OrderByDescending(c => c.CategoryName);
                    subcategory = subcategory.OrderByDescending(s => s.SubCategoryName);
                    break;
            }

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(brand.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult Create()
        {
            ViewBag.categoryList = db.Categories.ToList();
            ViewBag.subCategoryList = db.SubCategories.ToList();
            return View();
        }
        [HttpPost]
        public ActionResult Create(Brand brand)
        {
            if (ModelState.IsValid)
            {
                db.Brands.Add(brand);
                db.SaveChanges();
                return PartialView("_createSuccess");
            }
            ViewBag.categoryList = db.Categories.ToList();
            ViewBag.subCategoryList = db.SubCategories.ToList();
            return PartialView("_createError");
        }
        public ActionResult Edit(int id)
        {
            var brand = db.Brands.Find(id);
            ViewBag.categoryList = db.Categories.ToList();
            ViewBag.subCategoryList = db.SubCategories.ToList();
            return View(brand);
        }
        [HttpPost]
        public ActionResult Edit(Brand b)
        {
            if (ModelState.IsValid)
            {

                db.Entry(b).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return PartialView("_editSuccess");
            }
            ViewBag.categoryList = db.Categories.ToList();
            ViewBag.subCategoryList = db.SubCategories.ToList();
            return PartialView("_editError");
        }

        public ActionResult Delete(int id)
        {
            var brand = db.Brands.Find(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        // POST: Brand/Delete/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public ActionResult ConfirmDelete(int id)
        {
            var brand = db.Brands.Find(id);
            if (brand == null)
            {
                return HttpNotFound();
            }

            db.Brands.Remove(brand);
            db.SaveChanges();

            return PartialView("_deleteSuccess");
        }
    }
}

ElectroMart/Controllers/ViewProductController.cs
using ElectroMart.Models.InputModel;
using ElectroMart.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace ElectroMart.Controllers
{
    public class ViewProductController : Controller
    {
  
    
        // GET: ViewProduct
        EcommerceDbContext db;

        List<ShoppingCartModel> ListOfCart = new List<ShoppingCartModel>();
        List<RetriveProductView> ListofProduct = new List<RetriveProductView>();

        public ViewProductController()
        {
            db = new EcommerceDbContext();
            ListOfCart = new List<ShoppingCartModel>();
            ListofProduct = new List<RetriveProductView>();
        }
        [Authorize]
        public ActionResult Index()
        {
            IEnumerable<RetriveProductView> product = (
                                                        from p in db.Products
                                                        join pi in db.ProductImages on p.ProductId equals pi.ProductId
                                                        select new RetriveProductView
                                                        {
                                                            ProductId = p.ProductId,
                                                            ProductName = p.ProductName,
                                                            CategoryName = p.Category.CategoryName,
                                                            SubCategoryName = p.SubCategory.SubCategoryName,
                                                            BrandName = p.Brand.BrandName,
                                                            QuantityPerUnit = p.QuantityPerUnit,
                                                            UnitPrice = p.UnitPrice,
                                                            QuantityInStock = pi.QuantityInStock,
                                                            StockInStatus = pi.StockInStatus,
                                                            Description = pi.Description,
                                                            StoreDate = pi.StoreDate,
                                                            Images = pi.Images

                                                        }).ToList();

            //ViewBag.categoryList = db.Categories.ToList
            return View(product);
        }

        [HttpPost]


        public JsonResult CartView(int Id)
        {

            ShoppingCartModel objShoppingCartModel = new ShoppingCartModel();
            Product objPro = db.Products.SingleOrDefault(Model => Model.ProductId == Id);
            ProductImage objImg = db.ProductImages.SingleOrDefault(Model => Model.ProductId == Id);
            if (Session["CartCounter"] != null)
            {
                ListOfCart = Session["CartItem"] as List<ShoppingCartModel>;
            }
            if (ListOfCart.Any(x => x.Id == Id))
            {
                objShoppingCartModel = ListOfCart.Single(x => x.Id == Id);
                objShoppingCartModel.Quantity = objShoppingCartModel.Quantity + 1;
                objShoppingCartModel.Total = objShoppingCartModel.Quantity * objShoppingCartModel.UnitPrice;
            }
            else
            {
                objShoppingCartModel.Id = Id;
                objShoppingCartModel.ImagePath = objImg.Images;
                objShoppingCartModel.ProductsName = objPro.ProductName;
                objShoppingCartModel.Quantity = 1;
                objShoppingCartModel.UnitPrice = objPro.UnitPrice;
                objShoppingCartModel.Total = objPro.UnitPrice;
                ListOfCart.Add(objShoppingCartModel);
            }

            Session["CartCounter"] = ListOfCart.Count;
            Session["CartItem"] = ListOfCart;
            return Json(new { Success = true, Counter = ListOfCart.Count }, JsonRequestBehavior.AllowGet);
        }
        //[HttpPost]
        //public JsonResult OrderNow(OrderViewModel model)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        // Process the order
        //        // Return success message
        //        return Json(new { success = true, message = "Order placed successfully!" });
        //    }
        //    else
        //    {
        //        // Return error message
        //        return Json(new { success = false, message = "Error placing order. Please try again." });
        //    }
        //}


        public ActionResult ShoppingCart()
        {
            ListOfCart = Session["CartItem"] as List<ShoppingCartModel>;
            return View(ListOfCart);
        }
        [HttpPost]
        [ActionName("ShoppingCart")]
        public ActionResult AddOrder()
        {
            int OrderId = 0;

            ListOfCart = Session["CartItem"] as List<ShoppingCartModel>;
            Order ord = new Order
            {
                OrderDate = DateTime.Now,
                OrderNumber = String.Format("{0:ddmmyyyyHHmmsss}", DateTime.Now)
            };
            db.Orders.Add(ord);
            db.SaveChanges();
            OrderId = ord.OrderId;

            foreach (var item in ListOfCart)
            {
                OrderDetailModel orderDetail = new OrderDetailModel();
                orderDetail.Total = item.Total;
                orderDetail.ProductId = item.Id;
                orderDetail.OrderId = OrderId;
                orderDetail.Quantity = item.Quantity;
                orderDetail.UnitPrice = item.UnitPrice;
                db.OrderDetailModels.Add(orderDetail);
                db.SaveChanges();
            }

            Session["CartCounter"] = null;

            Session["CartItem"] = null;

            return PartialView("_orderResult");
        }
        //public JsonResult addtocartajax(int Id)
        //{
        //    return Json(new { Success = true, data = "hello", id= Id });
        //}

        [Authorize]
        public ActionResult ShowProduct(int? id)
        {
            Product p = db.Products.Find(id);
            ProductImage pi = db.ProductImages.Find(id);
            RetriveProductView pvm = new RetriveProductView
            {
                ProductId = p.ProductId,
                ProductName = p.ProductName,
                CategoryName = p.Category.CategoryName,
                SubCategoryName = p.SubCategory.SubCategoryName,
                BrandName = p.Brand.BrandName,
                QuantityPerUnit = p.QuantityPerUnit,
                UnitPrice = p.UnitPrice,
                QuantityInStock = (double)pi.QuantityInStock,
                StockInStatus = (bool)pi.StockInStatus,
                Description = pi.Description,
                StoreDate = (DateTime)pi.StoreDate,
                Images = pi.Images
            };
            return View(pvm);
        }


        public ActionResult RemoveFromCart(int id)
        {
            ListOfCart = Session["CartItem"] as List<ShoppingCartModel>;
            var removeItem = ListOfCart.FirstOrDefault(x => x.Id == id);
            ListOfCart.Remove(removeItem);
            ListOfCart = Session["CartItem"] as List<ShoppingCartModel>;
            return RedirectToAction(nameof(ShoppingCart));
        }

        [Authorize]
        public ActionResult Category(string sortOrder, /*string currentFilter,*/ string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name" : "";
            ViewBag.CurrentFilter = searchString;

            var categories = from s in db.Categories
                             select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                categories = categories.Where(x => x.CategoryName.ToLower().StartsWith(searchString.ToLower()));
            }
            switch (sortOrder)
            {
                case "name":
                    categories = categories.OrderByDescending(s => s.CategoryName);
                    break;

                default:  // Name ascending 
                    categories = categories.OrderBy(s => s.CategoryName);
                    break;
            }

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(categories.ToPagedList(pageNumber, pageSize));

        }
        [Authorize]
        public ActionResult Brand(string sortOrder, /*string currentFilter,*/ string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name" : "";

            ViewBag.CategorySortParm = String.IsNullOrEmpty(sortOrder) ? "category" : "";
            ViewBag.SubCategorySortParm = String.IsNullOrEmpty(sortOrder) ? "subcategory" : "";

            ViewBag.CurrentFilter = searchString;

            var brand = from s in db.Brands
                        select s;
            var category = from c in db.Categories select c;
            var subcategory = from s in db.SubCategories select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                brand = brand.Where(x => x.BrandName.ToLower().StartsWith(searchString.ToLower()));

            }
            switch (sortOrder)
            {
                case "name":
                    brand = brand.OrderBy(b => b.BrandName);
                    break;


                default:  // Name des_cending 
                    brand = brand.OrderByDescending(s => s.BrandName);
                    category = category.OrderByDescending(c => c.CategoryName);
                    subcategory = subcategory.OrderByDescending(s => s.SubCategoryName);
                    break;
            }

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(brand.ToPagedList(pageNumber, pageSize));
        }
        [Authorize]

ElectroMart/Views/ViewProduct/Brand.cshtml
@model PagedList.IPagedList<ElectroMart.Models.InputModel.Brand>
@using PagedList;
@using PagedList.Mvc;
@{
    ViewBag.Title = "Brand";
}

<div class="container" style="margin-top:65px;">
    <div class="row">
        <div class="col">
            @using (Html.BeginForm())
            {<div class="row mb-2">
                    <div class="col-md-11">
                        @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control r", placeholder = "Search by Brand Name..." })

                    </div>
                    <div class="col-md-1">
                        <button type="submit" class="btn alert-success">Search</button>
                    </div>

                </div>
            }
        </div>
    </div>
</div>

<div class="card container">

    <div class="card-header alert-secondary">
        <h1 class="card-title text-center text-light">Brand List</h1>

    </div>
    <div class="card-body ">
        <div class="row">


            <table class="table table-bordered table-striped">
                <thead class="alert-success">
                    <tr>
                        <th>ID</th>
                        <th>Category</th>
                        <th>Sub Category</th>
                        <th>
                            @Html.ActionLink("Brand", "Brand", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
                        </th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var brand in Model)
                    {
                        <tr>
                            <td>@Html.DisplayFor(x => brand.Id)</td>
                            <td>@Html.DisplayFor(x => brand.Category.CategoryName)</td>
                            <td>@Html.DisplayFor(x => brand.SubCategory.SubCategoryName)</td>
                            <td>@Html.DisplayFor(x => brand.BrandName)</td>

                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer alert-secondary" style="padding:5px">

        <div class="d-flex justify-content-between container">

            @Html.PagedListPager(Model, page => Url.Action("Brand", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

            Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

        </div>

    </div>
</div>

ElectroMart/Views/ViewProduct/Category.cshtml
@model PagedList.IPagedList<ElectroMart.Models.InputModel.Category>
@using PagedList;
@using PagedList.Mvc;
@{
    ViewBag.Title = "Category";
}

<div class="container" style="margin-top:65px;">
    <div class="row">
        <div class="col">
            @using (Html.BeginForm())
            {<div class="row mb-2">
                    <div class="col-md-11">
                        @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control r", placeholder = "Search by Category Name..." })

                    </div>
                    <div class="col-md-1">
                        <button type="submit" class="btn alert-success">Search</button>
                    </div>

                </div>
            }
        </div>
    </div>
</div>

<div class="card container">
    <div class="card-header alert-info">
        <h1 class="card-title text-center">Category List</h1>

    </div>
    <div class="card-body">
        <div class="col-md-12">

            <table class="table table-bordered table-striped">
                <thead class="alert-success">
                    <tr>
                        <th>ID</th>
                        <th>
                            @Html.ActionLink("Category Name", "Category", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
                        </th>
                        <th>Description</th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var cat in Model)
                    {
                        <tr>
                            <td>@Html.DisplayFor(x => cat.Id)</td>
                            <td>@Html.DisplayFor(x => cat.CategoryName)</td>
                            <td>@Html.DisplayFor(x => cat.CategoryDescription)</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer alert-info" style="padding:5px">

        <div class="d-flex justify-content-between container">

            @Html.PagedListPager(Model, page => Url.Action("Category", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

            Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

        </div>

    </div>
</div>

ElectroMart/Views/ViewProduct/Index.cshtml
@model IEnumerable<ElectroMart.Models.RetriveProductView>

@{
    ViewBag.Title = "Index";
}

<div class="container" style="margin-top:70px;">
    <h4 class="display-4 text-center pt-3 pb-4" style="color: darkred;font-weight:bold;">Product Information</h4>
    <div class="row">

        @foreach (var p in Model)
        {
            <div class="col-md-4 col-xs-6 border-primary mb-3">
                <div class="card" style="max-width:540px;">
                    <div class="row g-0">

                        <div class="col-md-12">
                            <div class="card-header text-white" style="background-color: #32cd32 ">
                                <p class="card-text">
                                    <h5 class="card-title text-capitalize text-center">@Html.DisplayFor(x => p.BrandName)</h5>
                                </p>
                            </div>
                        </div>

                        <div class="col-md-6">

                            <img src="@Url.Content(p.Images)" width="200" height="300" alt="" />
                        </div>

                        <div class="col-md-6">
                            <div class="card-body">
                                <p class="card-text"><b>Product Name: </b>@Html.DisplayFor(x => p.ProductName)</p>
                                <p class="card-text"><b>Quantity: </b>@Html.DisplayFor(x => p.QuantityInStock)</p>
                                <p class="card-text"><b>Store Date: </b>@Html.DisplayFor(x => p.StoreDate)</p>
                                <p class="card-text"><b>Store Date: </b>TK-@Html.DisplayFor(x => p.UnitPrice)</p>
                                <p class="card-text">
                                    <b>Status: </b>
                                    @if (p.QuantityInStock != 0)
                                    {
                                        <span class="badge bg-success text-white fw-bold">Available</span>
                                    }
                                    else
                                    {
                                        <span class="badge bg-danger text-white fw-bold">Not Available</span>
                                    }
                                </p>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="card-body">
                                <p class="card-text">
                                    <b>Product Description: </b><br>
                                    @Html.DisplayFor(x => p.Description)
                                </p>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="card-footer" style="background-color: #32cd32 ">
                                <p class="card-text">
                                    <a href="@Url.Action("ShowProduct","ViewProduct",new { id=p.ProductId})" class="btn float-right" style="background-color: #a52a2a; color: white; font-weight: bold;">Show Details</a>
                                    <input type="button" name="Add to cart" value="Add to Cart" class="btn" style="background-color: #0000ff;font-weight:bold; color: white;" itemid="@p.ProductId" id="btnAddToCart" Onclick="AddToCart(this)" />
                                </p>
                            </div>
                        </div>

                    </div>
                </div>

            </div>
        }

    </div>
</div>

@section scripts{

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js">
    </script>

    <script type="text/javascript">

        function AddToCart(item) {
            var itemId = $(item).attr("itemid");
            var formData = new FormData();
            formData.append("Id", itemId);

            fetch("/ViewProduct/CartView", {
                method: "post",
                body: formData,
            }).then(res => res.json())
                .then(data => {

                    document.getElementById("cartItem").innerHTML = "Cart(" + data.Counter + ")";
                })
        }
    </script>
}

ElectroMart/Views/ViewProduct/ShoppingCart.cshtml
@model IEnumerable<ElectroMart.Models.ShoppingCartModel>

@{
    ViewBag.Title = "ShoppingCart";
    double TotalAmount = 0.00;
}


<div class="container" style="margin-top:75px;">

    <h4 class="display-4 text-center pt-3 pb-4 mb-4" style="color: darkred;font-weight:bold;">Shopping Cart List</h4>

    <table class="table table-bordered table-striped">
        <thead class="bg-success text-center">
            <tr style="color:white;">
                <th>Product Image</th>
                <th>Product Name</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Amount</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var cart in Model)
            {
                TotalAmount += cart.Total;
                <tr>
                    <td>
                        <img src="@Url.Content(cart.ImagePath)" width="80" height="50" class="img-fluid" />
                    </td>
                    <td>
                        @cart.ProductsName
                    </td>
                    <td>@cart.Quantity</td>
                    <td>@cart.UnitPrice.ToString("#,##0.00")</td>
                    <td>@cart.Total.ToString("#,##0.00")</td>
                    <td class="d-flex justify-content-center">
                        <a class="btn btn-danger btn-sm" href="@Url.Action("RemoveFromCart", "ViewProduct", new { id = cart.Id })">Remove</a>
                    </td>

                </tr>
            }

            <tr style="border-top: 2px solid #b62626">
                <td colspan="4" style="text-align: right;" class="text-primary">
                    <h5>Total Amount</h5>
                </td>
                <td class="text-center">
                    <h5>@TotalAmount.ToString("#,##0.00")</h5>
                </td>
                <td></td>
            </tr>
        </tbody>
    </table>



    @using (Ajax.BeginForm(new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "msg", OnComplete = "orderAll" }))
    {
        <table class="table table-light">
        </table>
        <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-success  m-1">Order Now</button>
            <a href="@Url.Action("Index","ViewProduct")" class="btn btn-primary m-1 ">Back to Add Cart</a>
            <a href="@Url.Action("OrderDetails", "Products")" class="btn btn-warning m-1 ">Order Details</a>
        </div>

        <div class="row mb-2">
            <div class="col-10 offset-2" id="msg">

            </div>
        </div>
    }

    @*@using (Ajax.BeginForm(new AjaxOptions
        {
            HttpMethod = "POST",
            InsertionMode = InsertionMode.Replace,
            UpdateTargetId = "msg",
            OnSuccess = "orderSuccess",
            OnFailure = "orderFailure"
        }))
        {*@
    @*<table class="table table-light">*@
    <!-- Add your table content here -->
    <!--</table>
    <div class="d-flex justify-content-end">
        <button type="submit" class="btn btn-success btn-sm m-1">Order Now</button>
        <a href="@Url.Action("Index", "ViewProduct")" class="btn btn-link"><i class="fa fa-arrow-circle-left"></i> Back to Add Cart</a>
    </div>

    <div class="row mb-2">
        <div class="col-10 offset-2" id="msg">-->
    <!-- Message will be displayed here -->
    <!--</div>
        </div>
    }-->

</div>
@section scripts{

    <script src="~/Scripts/jquery-3.7.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>

    <script>
        function orderAll() {
            $("#form0").trigger("reset");
        }
    </script>
    <script type="text/javascript">
        function orderSuccess(response) {
            // Assuming response contains a message property with the success message
            var msgDiv = document.getElementById("msg");
            msgDiv.innerHTML = '<div class="alert alert-success" role="alert">' + response.message + '</div>';
        }

        function orderFailure(response) {
            // Assuming response contains a message property with the error message
            var msgDiv = document.getElementById("msg");
            msgDiv.innerHTML = '<div class="alert alert-danger" role="alert">' + response.responseText + '</div>';
        }
    </script>


}