ElectroMart/Models/InputModel/Category.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Drawing.Drawing2D;
using System.Linq;
using System.Web;

namespace ElectroMart.Models.InputModel
{
    public class Category
    {
        public int Id { get; set; }
        [Required, Display(Name = "Category")]
        public string CategoryName { get; set; }
        [Required, Display(Name = "Description")]
        public string CategoryDescription { get; set; }

        //nev
        public virtual ICollection<SubCategory> SubCategories { get; set; } = new List<SubCategory>();
        public virtual ICollection<Brand> Brands { get; set; } = new List<Brand>();
        public virtual ICollection<Product> Products { get; set; } = new List<Product>();
    }
}

ElectroMart/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using ElectroMart.Models.InputModel;
using PagedList;

namespace ElectroMart.Controllers
{
    public class CategoryController : Controller
    {
        private EcommerceDbContext db = new EcommerceDbContext();

        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {

            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name" : "";
            ViewBag.CurrentFilter = searchString;

            var categories = from s in db.Categories
                             select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                categories = categories.Where(x => x.CategoryName.ToLower().StartsWith(searchString.ToLower()));
            }
            switch (sortOrder)
            {
                case "name":
                    categories = categories.OrderByDescending(s => s.CategoryName);
                    break;

                default:  // Name ascending 
                    categories = categories.OrderBy(s => s.CategoryName);
                    break;
            }

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(categories.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Category cat)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(cat);
                db.SaveChanges();
                return PartialView("_createSuccess");
            }
            return PartialView("_createError");
        }
        public ActionResult Edit(int id)
        {
            var category = db.Categories.Find(id);
            return View(category);
        }
        [HttpPost]
        public ActionResult Edit(Category c)
        {
            if (ModelState.IsValid)
            {
                db.Entry(c).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return PartialView("_editSuccess");
            }
            return View(c);
        }
        // GET: Category/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = await db.Categories.FindAsync(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }


        // POST: Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Category category = await db.Categories
                .Include(c => c.SubCategories)
                .FirstOrDefaultAsync(c => c.Id == id);

            if (category != null)
            {
                // First, delete all related SubCategories
                db.SubCategories.RemoveRange(category.SubCategories);

                // Then delete the Category itself
                db.Categories.Remove(category);

                await db.SaveChangesAsync();

                // Set the success message
                return PartialView("_deleteSuccess");
                //TempData["SuccessMessage"] = "Category deleted successfully.";
            }

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }



    }
}

ElectroMart/Controllers/SubCategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using ElectroMart.Models.InputModel;
using PagedList;

namespace ElectroMart.Controllers
{
    public class SubCategoryController : Controller
    {
        private EcommerceDbContext db = new EcommerceDbContext();

        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;

            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name" : "";

            ViewBag.CurrentFilter = searchString;

            var subcategories = from s in db.SubCategories
                                select s;


            if (!String.IsNullOrEmpty(searchString))
            {
                subcategories = subcategories.Where(x => x.SubCategoryName.ToLower().StartsWith(searchString.ToLower()));

            }

            switch (sortOrder)
            {
                case "name":
                    subcategories = subcategories.OrderByDescending(s => s.SubCategoryName);

                    break;


                default:  // Name ascending 
                    subcategories = subcategories.OrderBy(s => s.SubCategoryName);

                    break;
            }

            int pageSize = 20;
            int pageNumber = (page ?? 1);

            return View(subcategories.ToPagedList(pageNumber, pageSize));

        }
        public ActionResult Create()
        {
            ViewBag.categoryList = db.Categories.ToList();
            return View();
        }
        [HttpPost]
        public ActionResult Create(SubCategory subCategory)
        {
            if (ModelState.IsValid)
            {
                db.SubCategories.Add(subCategory);
                db.SaveChanges();
                return PartialView("_createSuccess");
            }
            ViewBag.categoryList = db.Categories.ToList();
            return PartialView("_createError");

        }
        public ActionResult Edit(int id)
        {
            var s = db.SubCategories.Find(id);
            ViewBag.categoryList = db.Categories.ToList();
            return View(s);
        }
        [HttpPost]
        public ActionResult Edit(SubCategory s)
        {
            if (ModelState.IsValid)
            {
                db.Entry(s).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return PartialView("_editSuccess");
            };
            ViewBag.categoryList = db.Categories.ToList();
            return View(s);
        }
        //public async Task<ActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Category category = await db.Categories.FindAsync(id);
        //    if (category == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(category);
        //}

        //// POST: Category/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<ActionResult> DeleteConfirmed(int id)
        //{
        //    Category category = await db.Categories
        //        .Include(c => c.SubCategories)
        //        .FirstOrDefaultAsync(c => c.Id == id);

        //    if (category == null)
        //    {
        //        return HttpNotFound();
        //    }

        //    // Delete all related SubCategories
        //    db.SubCategories.RemoveRange(category.SubCategories);

        //    // Delete the Category itself
        //    db.Categories.Remove(category);

        //    await db.SaveChangesAsync();

        //    return RedirectToAction("Index");
        //}

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
        ////public async Task<ActionResult> Delete(int? id)
        ////{
        ////    if (id == null)
        ////    {
        ////        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        ////    }
        ////    SubCategory subCategory = await db.SubCategories.FindAsync(id);
        ////    if (subCategory == null)
        ////    {
        ////        return HttpNotFound();
        ////    }
        ////    return View(subCategory);
        ////}

        //// POST: SubCategory/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<ActionResult> DeleteConfirmed(int id)
        //{
        //    SubCategory subCategory = await db.SubCategories
        //        .Include(sc => sc.Brands)
        //        .Include(sc => sc.Products)
        //        .FirstOrDefaultAsync(sc => sc.Id == id);

        //    if (subCategory == null)
        //    {
        //        return HttpNotFound();
        //    }

        //    // Delete all related Brands
        //    db.Brands.RemoveRange(subCategory.Brands);

        //    // Delete all related Products
        //    db.Products.RemoveRange(subCategory.Products);

        //    // Delete the SubCategory itself
        //    db.SubCategories.Remove(subCategory);

        //    await db.SaveChangesAsync();

        //    // Set the success message if needed (optional)

        //    // Return a partial view indicating successful deletion
        //    return PartialView("_deleteSuccess");
        //}

        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<ActionResult> DeleteConfirmed(int id)
        //{
        //    SubCategory subCategory = await db.SubCategories
        //        .Include(sc => sc.Brands)
        //        .Include(sc => sc.Products)
        //        .FirstOrDefaultAsync(sc => sc.Id == id);

        //    if (subCategory == null)
        //    {
        //        return HttpNotFound();
        //    }

        //    // Delete all related Brands
        //    db.Brands.RemoveRange(subCategory.Brands);

        //    // Delete all related Products
        //    db.Products.RemoveRange(subCategory.Products);

        //    // Delete the SubCategory itself
        //    db.SubCategories.Remove(subCategory);

        //    await db.SaveChangesAsync();

        //    // Return the _deleteSuccess partial view
        //    return PartialView("_deleteSuccess");
        //}




        //[HttpPost, ActionName("Delete")]
        //    [ValidateAntiForgeryToken]
        //    public async Task<ActionResult> DeleteConfirmed(int id)
        //    {
        //        SubCategory subCategory = await db.SubCategories
        //            .Include(sc => sc.Brands)
        //            .Include(sc => sc.Products)
        //            .FirstOrDefaultAsync(sc => sc.Id == id);

        //        if (subCategory == null)
        //        {
        //            return HttpNotFound();
        //        }

        //        // Delete all related Brands
        //        db.Brands.RemoveRange(subCategory.Brands);

        //        // Delete all related Products
        //        db.Products.RemoveRange(subCategory.Products);

        //        // Delete the SubCategory itself
        //        db.SubCategories.Remove(subCategory);

        //        await db.SaveChangesAsync();

        //        // Return the _deleteSuccess partial view
        //        return PartialView("_deleteSuccess");
        //    }



        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}





        //public async Task<ActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Category category = await db.Categories.FindAsync(id);
        //    if (category == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(category);
        //}

        //// POST: Category/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<ActionResult> DeleteConfirmed(int id)
        //{
        //    Category category = await db.Categories
        //        .Include(c => c.SubCategories)
        //        .FirstOrDefaultAsync(c => c.Id == id);

        //    if (category == null)
        //    {
        //        return HttpNotFound();
        //    }

        //    // Delete all related SubCategories
        //    db.SubCategories.RemoveRange(category.SubCategories);

        //    // Delete the Category itself
        //    db.Categories.Remove(category);

        //    await db.SaveChangesAsync();

        //    return RedirectToAction("Index");
        //}

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}


        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SubCategory subCategory = await db.SubCategories.FindAsync(id);
            if (subCategory == null)
            {
                return HttpNotFound();
            }
            return View(subCategory);
        }

        // POST: SubCategory/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {

ElectroMart/Views/Category/Create.cshtml
@model ElectroMart.Models.InputModel.Category

@{
    ViewBag.Title = "Create";
}

<style>
    .form-container {
        max-width: 800px;
        margin: auto;
        border: 2px solid #ddd;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0px 0px 10px rgba(0,0,0,0.1);
        background-color: #f9f9f9;
        margin-top: 75px;
    }

    .form-title {
        text-align: center;
        font-weight: bold;
        color: darkred;
        margin-bottom: 35px;
        margin-top: 10px;
    }

    .form-group {
        margin-bottom: 1rem;
    }

    .btn {
        margin-top: 1rem;
    }

    .back-to-list {
        margin-top: 1rem;
    }
</style>

<div class="form-container">
    <h2 class="display-3 form-title">Add Category</h2>

    @using (Ajax.BeginForm(new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "msg", OnComplete = "clearAll" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group row">
            @Html.LabelFor(x => x.CategoryName, "Category Name", htmlAttributes: new { @class = "control-label col-md-3 text-right" })
            <div class="col-md-9">
                @Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.CategoryName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(x => x.CategoryDescription, "Category Description", htmlAttributes: new { @class = "control-label col-md-3 text-right" })
            <div class="col-md-9">
                @Html.TextAreaFor(x => x.CategoryDescription, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.CategoryDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            <div class="col-9 offset-3" id="msg">
            </div>
        </div>

        <div class="form-group row">
            <div class="col-md-9 offset-md-3 text-right">
                <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save</button>
                <a href="@Url.Action("Index", "Category")" class="btn btn-warning">Cancel</a>
            </div>
        </div>

        <div class="d-flex justify-content-start back-to-list">
            <a href="@Url.Action("Index", "Category")" class="btn btn-link"><i class="fa fa-arrow-circle-left"></i> Back to list</a>
        </div>
    }
</div>

@section scripts {
    <script src="~/Scripts/jquery-3.7.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script>
        $("#form0").attr("enctype", "multipart/form-data")
        function clearAll() {
            $("#form0").trigger("reset");
        }
    </script>
}

ElectroMart/Views/Category/Delete.cshtml
@model ElectroMart.Models.InputModel.Category

@{
    ViewBag.Title = "Delete";
}

<style>
    .form-container {
        max-width: 800px;
        margin: auto;
        border: 2px solid #ddd;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0px 0px 10px rgba(0,0,0,0.1);
        background-color: #f9f9f9;
        margin-top: 75px;
    }

    .form-title {
        text-align: center;
        font-weight: bold;
        color: darkred;
        margin-bottom: 35px;
        margin-top: 10px;
    }

    .form-group {
        margin-bottom: 1rem;
    }

    .btn {
        margin-top: 1rem;
    }

    .back-to-list {
        margin-top: 1rem;
    }
</style>

<div class="form-container">
    <h2 class="display-3 form-title">Delete Category</h2>
    <h4>Are you sure you want to delete this category?</h4>

    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.CategoryName)</dt>
        <dd>@Html.DisplayFor(model => model.CategoryName)</dd>

        <dt>@Html.DisplayNameFor(model => model.CategoryDescription)</dt>
        <dd>@Html.DisplayFor(model => model.CategoryDescription)</dd>
    </dl>

    <div id="msg"></div>

    @using (Ajax.BeginForm("Delete", "Category", new AjaxOptions { HttpMethod = "POST", OnSuccess = "onDeleteSuccess" }, new { @id = "deleteForm" }))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.Id)
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" />
            <a href="@Url.Action("Index", "Category")" class="btn btn-warning">Cancel</a>
        </div>

        <div class="d-flex justify-content-start back-to-list">
            <a href="@Url.Action("Index", "Category")" class="btn btn-link"><i class="fa fa-arrow-circle-left"></i> Back to list</a>
        </div>
    }

</div>

@section scripts {
    <script src="~/Scripts/jquery-3.7.0.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>

    <script>
        function onDeleteSuccess(response) {
            $('#msg').html(response);
            setTimeout(function() {
                window.location.href = '@Url.Action("Index", "Category")';
            }, 2000); // Redirect after 2 seconds
        }
    </script>
}

ElectroMart/Views/Category/Details.cshtml
@model ElectroMart.Models.InputModel.Category

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CategoryDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryDescription)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ElectroMart/Views/Category/Edit.cshtml
@model ElectroMart.Models.InputModel.Category

@{
    ViewBag.Title = "Edit";
}

<style>
    .form-container {
        max-width: 800px;
        margin: auto;
        border: 2px solid #ddd;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0px 0px 10px rgba(0,0,0,0.1);
        background-color: #f9f9f9;
        margin-top: 75px;
    }

    .form-title {
        text-align: center;
        font-weight: bold;
        color: darkred;
        margin-bottom: 35px;
        margin-top: 10px;
    }

    .form-group {
        margin-bottom: 1rem;
    }

    .btn {
        margin-top: 1rem;
    }

    .back-to-list {
        margin-top: 1rem;
    }
</style>

<div class="form-container">
    <h2 class="display-3 form-title">Edit Category</h2>

    <div id="UpdateMessage"></div>

    @using (Ajax.BeginForm(new AjaxOptions
    {
        HttpMethod = "POST",
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "msg",
        OnSuccess = "handleEditSuccess",
        OnComplete = "clearAll"
    }))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(x => x.Id)

        <div class="form-group row">
            @Html.LabelFor(x => x.CategoryName, "Category Name", htmlAttributes: new { @class = "control-label col-md-3 text-right" })
            <div class="col-md-9">
                @Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.CategoryName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(x => x.CategoryDescription, "Category Description", htmlAttributes: new { @class = "control-label col-md-3 text-right" })
            <div class="col-md-9">
                @Html.TextAreaFor(x => x.CategoryDescription, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.CategoryDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            <div class="col-9 offset-3" id="msg"></div>
        </div>

        <div class="form-group row">
            <div class="col-md-9 offset-md-3 text-right">
                <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Update</button>
                <a href="@Url.Action("Index", "Category")" class="btn btn-warning">Cancel</a>
            </div>
        </div>

        <div class="d-flex justify-content-start back-to-list">
            <a href="@Url.Action("Index", "Category")" class="btn btn-link"><i class="fa fa-arrow-circle-left"></i> Back to list</a>
        </div>
    }
</div>

@section scripts {
    <script src="~/Scripts/jquery-3.7.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>

    <script>
        function clearAll() {
            $("#form0").trigger("reset");
        }

        function handleEditSuccess(response) {
            if (response.success) {
                $('#UpdateMessage').html(response.message);
                setTimeout(function() {
                    window.location.href = '@Url.Action("Index", "Category")';
                }, 2000);
            }
            
        }
    </script>

    <script>
        $("#form0").attr("enctype", "multipart/form-data");
    </script>
}

ElectroMart/Views/Category/Index.cshtml
@model PagedList.IPagedList<ElectroMart.Models.InputModel.Category>
@using PagedList;
@using PagedList.Mvc;

@{
    ViewBag.Title = "Index";
}

<nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-top:55px;">
    <div class="container">
        <a href="@Url.Action("Index","Home")" class="nav-link">
            <img src="~/Images/Logo.jpg" width="40" height="40" class="navbar-brand" />
        </a>


        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#menubar" aria-controls="menubar" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse mt-3" id="menubar">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    @Html.ActionLink("Products", "Index", "Products", new { area = "" }, new { @class = "nav-link" })
                </li>

                <li class="nav-item">
                    @Html.ActionLink("Categories", "Index", "Category", new { area = "" }, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Sub Category", "Index", "SubCategory", new { area = "" }, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Brand", "Index", "Brand", new { area = "" }, new { @class = "nav-link" })
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control mr-sm-2", placeholder = "Search Category" })
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>
<div class="container mt-4 d-flex justify-content-end">
    <a href="@Url.Action("Create","Category")" class="btn btn-primary text-end mb-4">Add New Category</a>
</div>
<div class="card container">
    <div class="card-header alert-info">
        <h1 class="card-title text-center">Category List</h1>

    </div>
    <div class="card-body">
        <div class="col-md-12">

            <table class="table table-bordered table-hover">
                <thead class="alert-info">
                    <tr class="text-center">
                        <th>ID</th>

                        <th class="text-center">
                            Category Name
                        </th>
                        
                        <th>Description</th>
                        <th width="200">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var cat in Model)
                    {
                        <tr>
                            <td>@Html.DisplayFor(x => cat.Id)</td>
                            <td>@Html.DisplayFor(x => cat.CategoryName)</td>
                            <td>@Html.DisplayFor(x => cat.CategoryDescription)</td>

                            <td class="d-flex justify-content-center ">
                                <a href="@Url.Action("Edit","Category",new { id=cat.Id})" class="btn btn-primary btn-sm ">
                                    <i class="fa fa-edit"></i> Edit
                                </a>
                                <a href="@Url.Action("Delete","Category",new { id=cat.Id})" class="btn btn-danger btn-sm" style="margin-left:8px;">
                                    <i class="fa fa-trash"></i> Delete
                                </a>
                            </td>
                        </tr>



                    }
                </tbody>

            </table>
            <div>
                <h6>
                    Sorting By : @Html.ActionLink("Category Name", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
                </h6>
            </div>
        </div>
    </div>
    <div class="card-footer alert-info" style="padding:5px">

        <div class="d-flex justify-content-between container">

            @Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

            Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

        </div>

    </div>
</div>

ElectroMart/Views/Category/_createError.cshtml
<div class="alert alert-success">
    <strong>Failed!</strong> The Category has been Created Not successfully.Please try again...
</div>

ElectroMart/Views/Category/_createSuccess.cshtml
<div class="alert alert-success">
    <strong>Success!</strong> The Category Data Inserted Successfully.
</div>

ElectroMart/Views/Category/_deleteSuccess.cshtml
@*<div class="text-warning fw-bold">
    Brand Data Deleted Successfully !!!
</div>*@


<div class="alert alert-success">
    <strong>Success!</strong> The Category has been deleted successfully.
</div>

ElectroMart/Views/Category/_editSuccess.cshtml
<div class="alert alert-success">
    <strong>Success!</strong> The Category Data Update Successfully.
</div>